# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 257)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setToolTipDuration(-1)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.comboBox_option_mouse_button = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_option_mouse_button.setObjectName("comboBox_option_mouse_button")
        self.comboBox_option_mouse_button.addItem("")
        self.comboBox_option_mouse_button.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_option_mouse_button, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.comboBox_option_mouse_action = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_option_mouse_action.setObjectName("comboBox_option_mouse_action")
        self.comboBox_option_mouse_action.addItem("")
        self.comboBox_option_mouse_action.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_option_mouse_action, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboBox_hotkey_start = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_hotkey_start.setFrame(True)
        self.comboBox_hotkey_start.setObjectName("comboBox_hotkey_start")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.comboBox_hotkey_start.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_hotkey_start, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBox_hotkey_stop = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_hotkey_stop.setObjectName("comboBox_hotkey_stop")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.comboBox_hotkey_stop.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_hotkey_stop, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_clickPoint_currentMousePoint = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_clickPoint_currentMousePoint.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_clickPoint_currentMousePoint.setChecked(True)
        self.radioButton_clickPoint_currentMousePoint.setObjectName("radioButton_clickPoint_currentMousePoint")
        self.gridLayout.addWidget(self.radioButton_clickPoint_currentMousePoint, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_interval_1_10 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_interval_1_10.setMaximum(10)
        self.spinBox_interval_1_10.setObjectName("spinBox_interval_1_10")
        self.gridLayout_3.addWidget(self.spinBox_interval_1_10, 1, 3, 1, 1)
        self.spinBox_interval_seconds = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_interval_seconds.setMaximum(60)
        self.spinBox_interval_seconds.setObjectName("spinBox_interval_seconds")
        self.gridLayout_3.addWidget(self.spinBox_interval_seconds, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 3, 1, 1)
        self.spinBox_interval_hours = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_interval_hours.setPrefix("")
        self.spinBox_interval_hours.setMaximum(24)
        self.spinBox_interval_hours.setObjectName("spinBox_interval_hours")
        self.gridLayout_3.addWidget(self.spinBox_interval_hours, 1, 0, 1, 1)
        self.spinBox_interval_minutes = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_interval_minutes.setMaximum(60)
        self.spinBox_interval_minutes.setObjectName("spinBox_interval_minutes")
        self.gridLayout_3.addWidget(self.spinBox_interval_minutes, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_7.setColumnStretch(1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionssdf = QtWidgets.QAction(MainWindow)
        self.actionssdf.setObjectName("actionssdf")
        self.actionsadas = QtWidgets.QAction(MainWindow)
        self.actionsadas.setObjectName("actionsadas")
        self.actionsaddsa = QtWidgets.QAction(MainWindow)
        self.actionsaddsa.setObjectName("actionsaddsa")
        self.actionsadsdas = QtWidgets.QAction(MainWindow)
        self.actionsadsdas.setObjectName("actionsadsdas")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Click Options"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mouse Button</p></body></html>"))
        self.comboBox_option_mouse_button.setItemText(0, _translate("MainWindow", "Left Button"))
        self.comboBox_option_mouse_button.setItemText(1, _translate("MainWindow", "Right Button"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mouse Action</p></body></html>"))
        self.comboBox_option_mouse_action.setItemText(0, _translate("MainWindow", "Single Click"))
        self.comboBox_option_mouse_action.setItemText(1, _translate("MainWindow", "Duble Click"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Click Hotkey"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Start Hotkey. ctrl+ </p></body></html>"))
        self.comboBox_hotkey_start.setItemText(0, _translate("MainWindow", "F1"))
        self.comboBox_hotkey_start.setItemText(1, _translate("MainWindow", "F2"))
        self.comboBox_hotkey_start.setItemText(2, _translate("MainWindow", "F3"))
        self.comboBox_hotkey_start.setItemText(3, _translate("MainWindow", "F4"))
        self.comboBox_hotkey_start.setItemText(4, _translate("MainWindow", "F5"))
        self.comboBox_hotkey_start.setItemText(5, _translate("MainWindow", "F6"))
        self.comboBox_hotkey_start.setItemText(6, _translate("MainWindow", "F7"))
        self.comboBox_hotkey_start.setItemText(7, _translate("MainWindow", "F8"))
        self.comboBox_hotkey_start.setItemText(8, _translate("MainWindow", "F9"))
        self.comboBox_hotkey_start.setItemText(9, _translate("MainWindow", "F10"))
        self.comboBox_hotkey_start.setItemText(10, _translate("MainWindow", "F11"))
        self.comboBox_hotkey_start.setItemText(11, _translate("MainWindow", "F12"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Stop Hotkey. ctrl+</p></body></html>"))
        self.comboBox_hotkey_stop.setCurrentText(_translate("MainWindow", "F1"))
        self.comboBox_hotkey_stop.setItemText(0, _translate("MainWindow", "F1"))
        self.comboBox_hotkey_stop.setItemText(1, _translate("MainWindow", "F2"))
        self.comboBox_hotkey_stop.setItemText(2, _translate("MainWindow", "F3"))
        self.comboBox_hotkey_stop.setItemText(3, _translate("MainWindow", "F4"))
        self.comboBox_hotkey_stop.setItemText(4, _translate("MainWindow", "F5"))
        self.comboBox_hotkey_stop.setItemText(5, _translate("MainWindow", "F6"))
        self.comboBox_hotkey_stop.setItemText(6, _translate("MainWindow", "F7"))
        self.comboBox_hotkey_stop.setItemText(7, _translate("MainWindow", "F8"))
        self.comboBox_hotkey_stop.setItemText(8, _translate("MainWindow", "F9"))
        self.comboBox_hotkey_stop.setItemText(9, _translate("MainWindow", "F10"))
        self.comboBox_hotkey_stop.setItemText(10, _translate("MainWindow", "F11"))
        self.comboBox_hotkey_stop.setItemText(11, _translate("MainWindow", "F12"))
        self.groupBox.setTitle(_translate("MainWindow", "Click Point"))
        self.radioButton_clickPoint_currentMousePoint.setText(_translate("MainWindow", "click where \n"
"the mouse is"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Click Interval"))
        self.label_2.setText(_translate("MainWindow", "Minutes"))
        self.label_3.setText(_translate("MainWindow", "Seconds"))
        self.label.setText(_translate("MainWindow", "Hours"))
        self.label_4.setText(_translate("MainWindow", "1/10 S"))
        self.actionssdf.setText(_translate("MainWindow", "ssdf"))
        self.actionsadas.setText(_translate("MainWindow", "sadas"))
        self.actionsaddsa.setText(_translate("MainWindow", "saddsa"))
        self.actionsadsdas.setText(_translate("MainWindow", "sadsdas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
